### ISSUE TITLE
v3.8.5o and v3.8.5q missing.

### ISSUE THREAD

**Issue by toontownlpz** [CoocooFroggy/ttr_update_files#1]

**Comment by CoocooFroggy** [comment]
Heya!
Here is v3.8.5o: 310040bb95d220c2fadfe40b266056b69570075b
Is there something specific you're missing?

And I just restarted the bot. Looks like it got stuck trying to upload v3.8.5q: 906805f4ecb9893f73b6613d6b10e2686513131.

Thanks for bringing this to my attention!
